#!/usr/bin/env bash
# scripts/bootstrap.sh
# One-shot local setup: verifies tooling, generates xcconfig from .env, generates Xcode project.
# Idempotent. Safe to re-run.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

red()   { printf "\033[31m%s\033[0m\n" "$*"; }
green() { printf "\033[32m%s\033[0m\n" "$*"; }
yel()   { printf "\033[33m%s\033[0m\n" "$*"; }

require() {
  local cmd="$1"
  local install_hint="$2"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    red "missing: $cmd"
    yel "  → $install_hint"
    exit 1
  fi
}

require xcodegen "brew install xcodegen"
require swiftlint "brew install swiftlint"
require supabase  "brew install supabase/tap/supabase"

# ── .env handling ────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  yel ".env not found — copying .env.example"
  cp .env.example .env
  yel "Edit .env with values from \`supabase status\`, then re-run this script."
  exit 1
fi

# shellcheck disable=SC1091
set -a; source .env; set +a

if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
  red "SUPABASE_URL or SUPABASE_ANON_KEY missing in .env"
  exit 1
fi

# ── ios/Config.xcconfig (gitignored) ─────────────────────────────────────────
mkdir -p ios
cat > ios/Config.xcconfig <<EOF
// Generated by scripts/bootstrap.sh — do not edit by hand.
SUPABASE_URL = ${SUPABASE_URL}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
EOF
green "wrote ios/Config.xcconfig"

# ── Xcode project ───────────────────────────────────────────────────────────
( cd ios && xcodegen generate )
green "regenerated ios/Growquest.xcodeproj"

green "done. open ios/Growquest.xcodeproj"
